# Your personal GitHub token
github_token: fb0b5bbea55a4c11883ccc2704838a8446fd0503
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: shop-loc

# Virtual machine IP
ip: 192.168.83.139

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 512
